frontend:
    build: client/
    volumes:
        - "client/src:/src"
        - "client/dist:/dist"
server:
    build: .
    ports:
        - "9000:9000"
    volumes:
        - "server:/go/src/github.com/domasx2/bugzez"
        - "client/dist:/client"
